/**
 * Proposal writer.
 *
 * Mirrors `improve/scan/card-writer.ts` conventions: atomic-write JSON +
 * regenerated markdown, append a row to `.index.jsonl` for audit.
 *
 * Unlike cards, proposals are **never merged**. Each call writes a new
 * file with a new `proposalId`. This keeps the history of attempts on
 * disk; a future sprint may mark earlier attempts `superseded` via a
 * triage-style flow. This sprint never auto-supersedes.
 *
 * ## Proposal ID generation
 *
 * Default: `<cardSlug>-<yyyymmdd>-<6hexBytes>`. Tests can inject
 * `idGenerator` / `now` for determinism.
 *
 * ## Read-side helpers
 *
 *   - `listProposals()` — tabular index sorted newest-first.
 *   - `getProposal(id)` — single proposal by id.
 *   - `getProposalsForCard(slug)` — every proposal pointing at a card.
 *
 * Read helpers swallow corrupt-JSON cases silently — they show up as a
 * count mismatch against `.index.jsonl` for anyone investigating. This
 * matches the card-writer convention.
 *
 * @module improve/propose/writer
 */

import { randomBytes } from 'crypto';
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  renameSync,
  writeFileSync,
} from 'fs';
import { join } from 'path';
import {
  type ImprovementProposal,
  ImprovementProposalSchema,
  type ProposalIndexEvent,
  ProposalIndexEventSchema,
} from '../schemas.js';
import {
  getProposalJsonPath,
  getProposalMarkdownPath,
  getProposalsDir,
  getProposalsIndexPath,
} from '../paths.js';

export interface WriteProposalOutcome {
  proposalId: string;
  jsonPath: string;
  markdownPath: string;
}

/**
 * Persist a proposal to disk. Returns the file paths so callers can
 * surface them in CLI output. Throws if the directory cannot be
 * created or if the schema rejects the proposal.
 */
export function writeProposal(proposal: ImprovementProposal): WriteProposalOutcome {
  const validated = ImprovementProposalSchema.parse(proposal);
  const dir = getProposalsDir();
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  const jsonPath = getProposalJsonPath(validated.proposalId);
  const mdPath = getProposalMarkdownPath(validated.proposalId);

  atomicWriteJson(jsonPath, validated);
  atomicWriteText(mdPath, renderProposalMarkdown(validated));
  appendIndex({
    timestamp: new Date().toISOString(),
    event: 'created',
    proposalId: validated.proposalId,
    cardSlug: validated.cardSlug,
    generatedBy: validated.generatedBy,
    riskLevel: validated.riskLevel,
  });

  return { proposalId: validated.proposalId, jsonPath, markdownPath: mdPath };
}

/**
 * Deterministic id generator. Default uses `crypto.randomBytes(3)` →
 * 6 hex chars. Tests inject their own.
 */
export interface IdContext {
  /** Override the timestamp source. */
  now?: () => Date;
  /** Override the random-suffix source. Must return exactly 6 lowercase hex chars. */
  randomSuffix?: () => string;
}

/**
 * Build a proposal id from a card slug. Format:
 *   `<cardSlug>-<yyyymmdd>-<6hex>`
 * The result matches `/^[a-z0-9][a-z0-9-]*$/` so long as `cardSlug`
 * already does.
 */
export function generateProposalId(cardSlug: string, ctx: IdContext = {}): string {
  const now = (ctx.now ?? (() => new Date()))();
  const yyyymmdd = formatYyyymmdd(now);
  const suffix =
    ctx.randomSuffix !== undefined ? ctx.randomSuffix() : randomBytes(3).toString('hex');
  if (!/^[0-9a-f]{6}$/.test(suffix)) {
    throw new Error(`generateProposalId: randomSuffix must be 6 lowercase hex chars (got '${suffix}')`);
  }
  return `${cardSlug}-${yyyymmdd}-${suffix}`;
}

function formatYyyymmdd(d: Date): string {
  const y = d.getUTCFullYear();
  const m = String(d.getUTCMonth() + 1).padStart(2, '0');
  const day = String(d.getUTCDate()).padStart(2, '0');
  return `${y}${m}${day}`;
}

// ---------------------------------------------------------------------------
// Markdown renderer (pure; testable in isolation)
// ---------------------------------------------------------------------------

export function renderProposalMarkdown(p: ImprovementProposal): string {
  const out: string[] = [];
  out.push(`# ${p.proposalId} — \`${p.riskLevel}\` — \`${p.status}\``);
  out.push('');
  out.push(p.title);
  out.push('');
  out.push(
    `**Card:** \`${p.cardSlug}\` · **Root cause class:** \`${p.rootCauseClass}\` · **Generated by:** \`${p.generatedBy}\` · **Created:** ${p.createdAt}`,
  );
  out.push('');

  out.push('## Hypothesis');
  out.push('');
  out.push(p.hypothesis);
  out.push('');

  out.push(p.fixSketch);
  out.push('');

  out.push('## Likely files');
  out.push('');
  if (p.likelyFiles.length === 0) {
    out.push('_(none suggested by the template)_');
  } else {
    out.push('| Path | Risk | Confidence | Rationale |');
    out.push('| --- | --- | --- | --- |');
    for (const f of p.likelyFiles) {
      const escapedPath = f.path.replace(/\|/g, '\\|');
      const escapedRationale = f.rationale.replace(/\n/g, ' ').replace(/\|/g, '\\|');
      out.push(`| \`${escapedPath}\` | ${f.riskTier} | ${f.confidence} | ${escapedRationale} |`);
    }
  }
  out.push('');

  out.push('## Evidence references');
  out.push('');
  for (const e of p.evidenceRefs) {
    out.push(`- card \`${e.cardSlug}\` · seqs ${e.eventIndices.join(', ')}${e.annotation ? ` · ${e.annotation}` : ''}`);
  }
  out.push('');

  out.push('## Validation plan');
  out.push('');
  out.push('**Unit tests:**');
  if (p.validationPlan.unitTests.length === 0) out.push('- _(none)_');
  for (const t of p.validationPlan.unitTests) out.push(`- \`${t}\``);
  out.push('');
  out.push('**Eval cases:**');
  if (p.validationPlan.evalCases.length === 0) {
    // Sprint 3 ships `eval-gen` but Sprint 2's template engine still writes
    // an empty list; the back-fill into validationPlan.evalCases is the
    // operator's call (a later sprint adds an atomic linker).
    out.push(`- _(none — generate one with \`afk improve eval-gen ${p.cardSlug}\`)_`);
  } else {
    for (const e of p.validationPlan.evalCases) out.push(`- ${e}`);
  }
  out.push('');
  out.push('**Smoke checks:**');
  if (p.validationPlan.smokeChecks.length === 0) out.push('- _(none)_');
  for (const s of p.validationPlan.smokeChecks) out.push(`- \`${s}\``);
  out.push('');
  out.push('**Manual checks:**');
  if (p.validationPlan.manualChecks.length === 0) out.push('- _(none)_');
  for (const m of p.validationPlan.manualChecks) out.push(`- ${m}`);
  out.push('');

  out.push('## Scope freeze');
  out.push('');
  out.push(
    `**Requires explicit approval:** ${p.scopeFreeze.requiresExplicitApproval ? '**yes**' : 'no'}`,
  );
  out.push('');
  out.push('**Forbidden paths** (never auto-edited by a future `apply`):');
  for (const path of p.scopeFreeze.forbiddenPaths) out.push(`- \`${path}\``);
  out.push('');

  out.push('## Triage notes');
  out.push('');
  if (p.notes.length === 0) {
    out.push('_(none)_');
  } else {
    for (const n of p.notes) out.push(`- _${n.at}_ — ${n.text}`);
  }
  out.push('');

  return out.join('\n');
}

// ---------------------------------------------------------------------------
// Read-side helpers
// ---------------------------------------------------------------------------

export interface ProposalListEntry {
  proposalId: string;
  cardSlug: string;
  title: string;
  riskLevel: ImprovementProposal['riskLevel'];
  status: ImprovementProposal['status'];
  rootCauseClass: ImprovementProposal['rootCauseClass'];
  generatedBy: ImprovementProposal['generatedBy'];
  createdAt: string;
}

export function listProposals(): ProposalListEntry[] {
  const dir = getProposalsDir();
  if (!existsSync(dir)) return [];
  const entries: ProposalListEntry[] = [];
  for (const name of readdirSync(dir)) {
    if (!name.endsWith('.json')) continue;
    if (name.startsWith('.')) continue;
    const p = readProposalIfExists(join(dir, name));
    if (!p) continue;
    entries.push({
      proposalId: p.proposalId,
      cardSlug: p.cardSlug,
      title: p.title,
      riskLevel: p.riskLevel,
      status: p.status,
      rootCauseClass: p.rootCauseClass,
      generatedBy: p.generatedBy,
      createdAt: p.createdAt,
    });
  }
  entries.sort((a, b) => {
    if (a.createdAt !== b.createdAt) return a.createdAt < b.createdAt ? 1 : -1;
    return a.proposalId < b.proposalId ? -1 : 1;
  });
  return entries;
}

export function getProposal(proposalId: string): ImprovementProposal | undefined {
  return readProposalIfExists(getProposalJsonPath(proposalId));
}

export function getProposalsForCard(cardSlug: string): ImprovementProposal[] {
  return listProposals()
    .filter((e) => e.cardSlug === cardSlug)
    .map((e) => getProposal(e.proposalId))
    .filter((p): p is ImprovementProposal => p !== undefined);
}

function readProposalIfExists(path: string): ImprovementProposal | undefined {
  if (!existsSync(path)) return undefined;
  try {
    const raw = readFileSync(path, 'utf-8');
    const parsed = JSON.parse(raw);
    const validated = ImprovementProposalSchema.safeParse(parsed);
    if (!validated.success) return undefined;
    return validated.data;
  } catch {
    return undefined;
  }
}

// ---------------------------------------------------------------------------
// Index append
// ---------------------------------------------------------------------------

function appendIndex(event: ProposalIndexEvent): void {
  const validated = ProposalIndexEventSchema.parse(event);
  const path = getProposalsIndexPath();
  const dir = getProposalsDir();
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  try {
    writeFileSync(path, JSON.stringify(validated) + '\n', { flag: 'a' });
  } catch {
    // Best-effort, matching card-writer.
  }
}

// ---------------------------------------------------------------------------
// Atomic write helpers (mirror card-writer.ts)
// ---------------------------------------------------------------------------

function atomicWriteJson(path: string, data: unknown): void {
  const tmp = `${path}.tmp-${process.pid}-${Date.now()}`;
  writeFileSync(tmp, JSON.stringify(data, null, 2));
  renameSync(tmp, path);
}

function atomicWriteText(path: string, text: string): void {
  const tmp = `${path}.tmp-${process.pid}-${Date.now()}`;
  writeFileSync(tmp, text);
  renameSync(tmp, path);
}
