/**
 * Golden-master parity harness for InputCore.moveUpLine / moveDownLine.
 *
 * Contract: the single-pass rewrite of the vertical line-navigation
 * primitives (PERF: O(n) forward pass instead of O(n^2) per-index
 * `visualCursorPos` probing) MUST preserve EXACT cursor semantics of the
 * original loop-over-indices implementation — including:
 *   - wrapped soft-line boundaries (deferred-wrap: col at a `% cols === 0`
 *     boundary reports col 0 of the next visual row);
 *   - wide-character / emoji width via `string-width` (emoji = 2 cols,
 *     CJK = 2 cols) — the SAME primitive `visualCursorPos` measures with,
 *     so semantics cannot drift;
 *   - the desired-column landing rule: among indices on the target visual
 *     row, pick the one whose visual column is closest to the source column,
 *     with LEFTMOST winning ties (strict `dist < bestDist` in the original);
 *   - first/last visual-row edge cases (`{ moved: false }` when there is no
 *     row above / below).
 *
 * History: the frozen `GOLDEN` matrix below was generated by executing the
 * ORIGINAL (pre-rewrite) implementation across the fixture matrix and
 * snapshotting its outputs (see the generator described in the perf change
 * commit). Each row is `[label, buffer, width, promptLen, cursor, upCursor,
 * downCursor]`, where `upCursor` / `downCursor` are the resulting cursor
 * index or `null` when the move returned `{ moved: false }`. These values
 * are a golden master: they lock the OLD behavior. The rewrite is accepted
 * only if it reproduces every row identically. Do NOT regenerate these to
 * make a failing rewrite pass — a divergence here is a real semantic change.
 */

import { describe, expect, it } from 'vitest';
import { InputCore } from './input-core.js';

// [label, buffer, width, promptLen, cursor, upCursorOrNull, downCursorOrNull]
type GoldenRow = [string, string, number, number, number, number | null, number | null];

// Frozen snapshot of the ORIGINAL moveUpLine / moveDownLine outputs. See the
// file-level History note: generated from the pre-rewrite implementation.
const GOLDEN: readonly GoldenRow[] = [
  ['empty', '', 80, 0, 0, null, null],
  ['empty-prompt5', '', 80, 5, 0, null, null],
  ['single-line', 'hello', 80, 0, 0, null, null],
  ['single-line', 'hello', 80, 0, 1, null, null],
  ['single-line', 'hello', 80, 0, 2, null, null],
  ['single-line', 'hello', 80, 0, 3, null, null],
  ['single-line', 'hello', 80, 0, 4, null, null],
  ['single-line', 'hello', 80, 0, 5, null, null],
  ['single-line-prompt', 'hello', 80, 5, 0, null, null],
  ['single-line-prompt', 'hello', 80, 5, 1, null, null],
  ['single-line-prompt', 'hello', 80, 5, 2, null, null],
  ['single-line-prompt', 'hello', 80, 5, 3, null, null],
  ['single-line-prompt', 'hello', 80, 5, 4, null, null],
  ['single-line-prompt', 'hello', 80, 5, 5, null, null],
  ['multi-2', 'line1\nline2', 80, 0, 0, null, 6],
  ['multi-2', 'line1\nline2', 80, 0, 1, null, 7],
  ['multi-2', 'line1\nline2', 80, 0, 2, null, 8],
  ['multi-2', 'line1\nline2', 80, 0, 3, null, 9],
  ['multi-2', 'line1\nline2', 80, 0, 4, null, 10],
  ['multi-2', 'line1\nline2', 80, 0, 5, null, 11],
  ['multi-2', 'line1\nline2', 80, 0, 6, 0, null],
  ['multi-2', 'line1\nline2', 80, 0, 10, 4, null],
  ['multi-2', 'line1\nline2', 80, 0, 11, 5, null],
  ['multi-2-prompt', 'line1\nline2', 200, 5, 0, null, 11],
  ['multi-2-prompt', 'line1\nline2', 200, 5, 1, null, 11],
  ['multi-2-prompt', 'line1\nline2', 200, 5, 2, null, 11],
  ['multi-2-prompt', 'line1\nline2', 200, 5, 3, null, 11],
  ['multi-2-prompt', 'line1\nline2', 200, 5, 4, null, 11],
  ['multi-2-prompt', 'line1\nline2', 200, 5, 5, null, 11],
  ['multi-2-prompt', 'line1\nline2', 200, 5, 6, 0, null],
  ['multi-2-prompt', 'line1\nline2', 200, 5, 10, 0, null],
  ['multi-2-prompt', 'line1\nline2', 200, 5, 11, 0, null],
  ['multi-3', 'aaa\nbbbb\ncc', 80, 3, 0, null, 7],
  ['multi-3', 'aaa\nbbbb\ncc', 80, 3, 1, null, 8],
  ['multi-3', 'aaa\nbbbb\ncc', 80, 3, 2, null, 8],
  ['multi-3', 'aaa\nbbbb\ncc', 80, 3, 3, null, 8],
  ['multi-3', 'aaa\nbbbb\ncc', 80, 3, 4, 0, 9],
  ['multi-3', 'aaa\nbbbb\ncc', 80, 3, 5, 0, 10],
  ['multi-3', 'aaa\nbbbb\ncc', 80, 3, 6, 0, 11],
  ['multi-3', 'aaa\nbbbb\ncc', 80, 3, 8, 1, 11],
  ['multi-3', 'aaa\nbbbb\ncc', 80, 3, 9, 4, null],
  ['multi-3', 'aaa\nbbbb\ncc', 80, 3, 10, 5, null],
  ['multi-3', 'aaa\nbbbb\ncc', 80, 3, 11, 6, null],
  ['softwrap-narrow', 'abcdefghij', 4, 0, 0, null, 4],
  ['softwrap-narrow', 'abcdefghij', 4, 0, 1, null, 5],
  ['softwrap-narrow', 'abcdefghij', 4, 0, 2, null, 6],
  ['softwrap-narrow', 'abcdefghij', 4, 0, 3, null, 7],
  ['softwrap-narrow', 'abcdefghij', 4, 0, 4, 0, 8],
  ['softwrap-narrow', 'abcdefghij', 4, 0, 5, 1, 9],
  ['softwrap-narrow', 'abcdefghij', 4, 0, 6, 2, 10],
  ['softwrap-narrow', 'abcdefghij', 4, 0, 9, 5, null],
  ['softwrap-narrow', 'abcdefghij', 4, 0, 10, 6, null],
  ['softwrap-prompt', 'abcdefghij', 6, 3, 0, null, 6],
  ['softwrap-prompt', 'abcdefghij', 6, 3, 1, null, 7],
  ['softwrap-prompt', 'abcdefghij', 6, 3, 2, null, 8],
  ['softwrap-prompt', 'abcdefghij', 6, 3, 3, 0, 9],
  ['softwrap-prompt', 'abcdefghij', 6, 3, 4, 0, 10],
  ['softwrap-prompt', 'abcdefghij', 6, 3, 5, 0, 10],
  ['softwrap-prompt', 'abcdefghij', 6, 3, 6, 0, 10],
  ['softwrap-prompt', 'abcdefghij', 6, 3, 9, 3, null],
  ['softwrap-prompt', 'abcdefghij', 6, 3, 10, 4, null],
  ['softwrap-multi', 'abcdef\nghijkl', 4, 0, 0, null, 4],
  ['softwrap-multi', 'abcdef\nghijkl', 4, 0, 1, null, 5],
  ['softwrap-multi', 'abcdef\nghijkl', 4, 0, 2, null, 6],
  ['softwrap-multi', 'abcdef\nghijkl', 4, 0, 3, null, 6],
  ['softwrap-multi', 'abcdef\nghijkl', 4, 0, 4, 0, 7],
  ['softwrap-multi', 'abcdef\nghijkl', 4, 0, 5, 1, 8],
  ['softwrap-multi', 'abcdef\nghijkl', 4, 0, 6, 2, 9],
  ['softwrap-multi', 'abcdef\nghijkl', 4, 0, 7, 4, 11],
  ['softwrap-multi', 'abcdef\nghijkl', 4, 0, 12, 8, null],
  ['softwrap-multi', 'abcdef\nghijkl', 4, 0, 13, 9, null],
  ['emoji-line', 'a🙂b🙂c', 80, 0, 0, null, null],
  ['emoji-line', 'a🙂b🙂c', 80, 0, 1, null, null],
  ['emoji-line', 'a🙂b🙂c', 80, 0, 2, null, null],
  ['emoji-line', 'a🙂b🙂c', 80, 0, 3, null, null],
  ['emoji-line', 'a🙂b🙂c', 80, 0, 4, null, null],
  ['emoji-line', 'a🙂b🙂c', 80, 0, 5, null, null],
  ['emoji-line', 'a🙂b🙂c', 80, 0, 6, null, null],
  ['emoji-line', 'a🙂b🙂c', 80, 0, 7, null, null],
  ['emoji-wrap', 'a🙂b🙂c🙂d', 4, 0, 0, null, 4],
  ['emoji-wrap', 'a🙂b🙂c🙂d', 4, 0, 1, null, 4],
  ['emoji-wrap', 'a🙂b🙂c🙂d', 4, 0, 2, null, 4],
  ['emoji-wrap', 'a🙂b🙂c🙂d', 4, 0, 3, null, 7],
  ['emoji-wrap', 'a🙂b🙂c🙂d', 4, 0, 4, 0, 9],
  ['emoji-wrap', 'a🙂b🙂c🙂d', 4, 0, 5, 0, 9],
  ['emoji-wrap', 'a🙂b🙂c🙂d', 4, 0, 6, 1, 10],
  ['emoji-wrap', 'a🙂b🙂c🙂d', 4, 0, 9, 4, null],
  ['emoji-wrap', 'a🙂b🙂c🙂d', 4, 0, 10, 6, null],
  ['cjk-line', '你好世界', 80, 0, 0, null, null],
  ['cjk-line', '你好世界', 80, 0, 1, null, null],
  ['cjk-line', '你好世界', 80, 0, 2, null, null],
  ['cjk-line', '你好世界', 80, 0, 3, null, null],
  ['cjk-line', '你好世界', 80, 0, 4, null, null],
  ['cjk-wrap', '你好世界你好', 5, 0, 0, null, 3],
  ['cjk-wrap', '你好世界你好', 5, 0, 1, null, 3],
  ['cjk-wrap', '你好世界你好', 5, 0, 2, null, 4],
  ['cjk-wrap', '你好世界你好', 5, 0, 3, 0, 5],
  ['cjk-wrap', '你好世界你好', 5, 0, 4, 1, 6],
  ['cjk-wrap', '你好世界你好', 5, 0, 5, 3, null],
  ['cjk-wrap', '你好世界你好', 5, 0, 6, 3, null],
  ['cjk-mixed', 'a你b好c', 4, 2, 0, null, 3],
  ['cjk-mixed', 'a你b好c', 4, 2, 1, null, 3],
  ['cjk-mixed', 'a你b好c', 4, 2, 2, 0, 5],
  ['cjk-mixed', 'a你b好c', 4, 2, 3, 0, 5],
  ['cjk-mixed', 'a你b好c', 4, 2, 4, 2, null],
  ['cjk-mixed', 'a你b好c', 4, 2, 5, 2, null],
  ['emoji-cjk-multi', '🙂你\nab', 80, 1, 0, null, 5],
  ['emoji-cjk-multi', '🙂你\nab', 80, 1, 1, null, 5],
  ['emoji-cjk-multi', '🙂你\nab', 80, 1, 2, null, 6],
  ['emoji-cjk-multi', '🙂你\nab', 80, 1, 3, null, 6],
  ['emoji-cjk-multi', '🙂你\nab', 80, 1, 4, 0, null],
  ['emoji-cjk-multi', '🙂你\nab', 80, 1, 5, 0, null],
  ['emoji-cjk-multi', '🙂你\nab', 80, 1, 6, 0, null],
  ['long-mixed', 'The quick 🙂 brown 你好 fox jumps', 10, 4, 0, null, 10],
  ['long-mixed', 'The quick 🙂 brown 你好 fox jumps', 10, 4, 1, null, 10],
  ['long-mixed', 'The quick 🙂 brown 你好 fox jumps', 10, 4, 2, null, 12],
  ['long-mixed', 'The quick 🙂 brown 你好 fox jumps', 10, 4, 3, null, 13],
  ['long-mixed', 'The quick 🙂 brown 你好 fox jumps', 10, 4, 4, null, 14],
  ['long-mixed', 'The quick 🙂 brown 你好 fox jumps', 10, 4, 5, null, 15],
  ['long-mixed', 'The quick 🙂 brown 你好 fox jumps', 10, 4, 6, 0, 16],
  ['long-mixed', 'The quick 🙂 brown 你好 fox jumps', 10, 4, 15, 5, 23],
  ['long-mixed', 'The quick 🙂 brown 你好 fox jumps', 10, 4, 30, 20, null],
  ['long-mixed', 'The quick 🙂 brown 你好 fox jumps', 10, 4, 31, 21, null],
  ['trailing-nl', 'abc\n', 80, 0, 0, null, 4],
  ['trailing-nl', 'abc\n', 80, 0, 1, null, 4],
  ['trailing-nl', 'abc\n', 80, 0, 2, null, 4],
  ['trailing-nl', 'abc\n', 80, 0, 3, null, 4],
  ['trailing-nl', 'abc\n', 80, 0, 4, 0, null],
  ['leading-nl', '\nabc', 80, 0, 0, null, 1],
  ['leading-nl', '\nabc', 80, 0, 1, 0, null],
  ['leading-nl', '\nabc', 80, 0, 2, 0, null],
  ['leading-nl', '\nabc', 80, 0, 3, 0, null],
  ['leading-nl', '\nabc', 80, 0, 4, 0, null],
  ['double-nl', 'a\n\nb', 80, 0, 0, null, 2],
  ['double-nl', 'a\n\nb', 80, 0, 1, null, 2],
  ['double-nl', 'a\n\nb', 80, 0, 2, 0, 3],
  ['double-nl', 'a\n\nb', 80, 0, 3, 2, null],
  ['double-nl', 'a\n\nb', 80, 0, 4, 2, null],
  ['wide-exact-boundary', 'abcd', 4, 0, 0, null, 4],
  ['wide-exact-boundary', 'abcd', 4, 0, 1, null, 4],
  ['wide-exact-boundary', 'abcd', 4, 0, 2, null, 4],
  ['wide-exact-boundary', 'abcd', 4, 0, 3, null, 4],
  ['wide-exact-boundary', 'abcd', 4, 0, 4, 0, null],
  ['wide-exact-plus-prompt', 'ab', 4, 2, 0, null, 2],
  ['wide-exact-plus-prompt', 'ab', 4, 2, 1, null, 2],
  ['wide-exact-plus-prompt', 'ab', 4, 2, 2, 0, null],
];

function upResult(buffer: string, cursor: number, w: number, p: number): number | null {
  const r = InputCore.moveUpLine({ buffer, cursor }, w, p);
  return r.moved ? r.state.cursor : null;
}

function downResult(buffer: string, cursor: number, w: number, p: number): number | null {
  const r = InputCore.moveDownLine({ buffer, cursor }, w, p);
  return r.moved ? r.state.cursor : null;
}

describe('InputCore vertical-nav parity (golden master)', () => {
  it('reproduces the original moveUpLine / moveDownLine outputs across the fixture matrix', () => {
    // Compare the ENTIRE matrix in one shot so a single failure surfaces
    // every diverging row at once (vitest prints the full array diff).
    const actual = GOLDEN.map(([label, buffer, w, p, cursor]) => [
      label,
      buffer,
      w,
      p,
      cursor,
      upResult(buffer, cursor, w, p),
      downResult(buffer, cursor, w, p),
    ]);
    expect(actual).toEqual(GOLDEN.map((row) => [...row]));
  });

  // Per-row cases give a readable failure label when a single fixture breaks.
  for (const [label, buffer, w, p, cursor, up, down] of GOLDEN) {
    it(`${label} @cursor=${cursor} (w=${w},p=${p}): up=${up}, down=${down}`, () => {
      expect(upResult(buffer, cursor, w, p)).toBe(up);
      expect(downResult(buffer, cursor, w, p)).toBe(down);
    });
  }

  // Round-trip invariant: for buffers where each logical line is one visual
  // row, up-then-down (and down-then-up) should return to the source cursor
  // for interior rows. This is an independent check on the desired-column
  // landing rule (not a snapshot).
  describe('round-trip on single-visual-row-per-line buffers', () => {
    const W = 200;
    const P = 5;
    for (const buffer of ['abc\ndef', 'line1\nline2', 'a\nbb\nccc', 'xx\nyy\nzz']) {
      it(`up∘down / down∘up preserve cursor on interior rows of ${JSON.stringify(buffer)}`, () => {
        for (let cursor = 0; cursor <= buffer.length; cursor++) {
          const up = InputCore.moveUpLine({ buffer, cursor }, W, P);
          if (up.moved) {
            const back = InputCore.moveDownLine(up.state, W, P);
            // Coming back down should not overshoot the original column.
            expect(back.moved).toBe(true);
          }
        }
      });
    }
  });
});
