/**
 * Tests for src/agent/gh.ts
 *
 * All tests inject `execFn` — no real `gh` invocations occur.
 */

import { describe, it, expect, vi, afterEach } from 'vitest';

import {
  checkGhReady,
  createPr,
  postPrComment,
  resolveCurrentBranchPr,
  GhError,
  _resetCacheForTest,
} from './gh.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Returns a mock execFn that resolves with the given output. */
function mockExec(stdout = '', stderr = '') {
  return vi.fn().mockResolvedValue({ stdout, stderr });
}

/** Returns a mock execFn that throws the given error. */
function mockExecThrows(err: unknown) {
  return vi.fn().mockRejectedValue(err);
}

// Each checkGhReady test must bypass the TTL cache; pass ttlMs: 0 everywhere.
const NO_CACHE = { ttlMs: 0 };

// File-scope reset: wipe module-level cache/inflight after every test so no
// test can leak state into the next one (regardless of which describe block
// they live in).
afterEach(() => {
  _resetCacheForTest();
});

// ---------------------------------------------------------------------------
// createPr
// ---------------------------------------------------------------------------

describe('createPr', () => {
  const baseOpts = {
    base: 'main',
    head: 'afk/farm/my-slug/1-branch-1',
    title: 'Auto PR: my-slug',
    body: 'Auto-generated by afk farm',
  };

  it('success — returns trimmed PR URL', async () => {
    const exec = mockExec('https://github.com/org/repo/pull/42\n', '');
    const result = await createPr(baseOpts, exec);
    expect(result).toBe('https://github.com/org/repo/pull/42');
    expect(exec).toHaveBeenCalledWith(
      'gh',
      expect.arrayContaining(['pr', 'create', '--base', 'main', '--head', 'afk/farm/my-slug/1-branch-1']),
    );
  });

  it('ENOENT — throws GhError with kind: not-found', async () => {
    const exec = mockExecThrows({ code: 'ENOENT' });
    await expect(createPr(baseOpts, exec)).rejects.toThrow(GhError);
    await expect(createPr(baseOpts, exec)).rejects.toMatchObject({ kind: 'not-found' });
  });

  it('unauthed — throws GhError with kind: unauthed', async () => {
    const exec = mockExecThrows({
      code: 'ENOENT',  // won't match since stderr is checked first — use non-ENOENT code
      stderr: 'authentication required: please log in to GitHub',
      exitCode: 1,
    });
    // Reset to non-ENOENT so stderr discrimination fires
    const exec2 = mockExecThrows({
      code: undefined,
      stderr: 'authentication required: please log in to GitHub',
      exitCode: 1,
    });
    await expect(createPr(baseOpts, exec2)).rejects.toMatchObject({ kind: 'unauthed' });
  });

  it('network error — throws GhError with kind: network', async () => {
    const exec = mockExecThrows({
      code: 'ETIMEDOUT',
      stderr: '',
      exitCode: 1,
    });
    await expect(createPr(baseOpts, exec)).rejects.toMatchObject({ kind: 'network' });
  });

  it('already-exists — throws GhError with kind: already-exists', async () => {
    const exec = mockExecThrows({
      code: undefined,
      stderr: 'a pull request for branch "afk/farm/my-slug/1-branch-1" already exists',
      exitCode: 1,
    });
    await expect(createPr(baseOpts, exec)).rejects.toMatchObject({ kind: 'already-exists' });
  });
});

// ---------------------------------------------------------------------------
// checkGhReady
// ---------------------------------------------------------------------------

describe('checkGhReady', () => {

  it('ENOENT on gh --version → ok: false with brew hint', async () => {
    const exec = mockExecThrows({ code: 'ENOENT' });
    const result = await checkGhReady({ execFn: exec, ...NO_CACHE });
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.hint).toMatch(/brew install gh/);
    }
  });

  it('auth failure on gh auth status → ok: false with gh auth login hint', async () => {
    // First call succeeds (gh --version), second call fails (gh auth status)
    const exec = vi
      .fn()
      .mockResolvedValueOnce({ stdout: 'gh version 2.40.0', stderr: '' })
      .mockRejectedValueOnce(new Error('not logged in'));
    const result = await checkGhReady({ execFn: exec, ...NO_CACHE });
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.hint).toMatch(/gh auth login/);
    }
  });

  it('both succeed → ok: true', async () => {
    const exec = vi
      .fn()
      .mockResolvedValueOnce({ stdout: 'gh version 2.40.0', stderr: '' })
      .mockResolvedValueOnce({ stdout: 'Logged in to github.com', stderr: '' });
    const result = await checkGhReady({ execFn: exec, ...NO_CACHE });
    expect(result).toEqual({ ok: true });
  });

  it('TTL cache: second call within TTL returns cached result without calling execFn again', async () => {
    const exec = vi
      .fn()
      .mockResolvedValueOnce({ stdout: 'gh version 2.40.0', stderr: '' })
      .mockResolvedValueOnce({ stdout: 'Logged in', stderr: '' });

    const now = Date.now();
    const _now = vi.fn().mockReturnValue(now);

    // First call: execFn called twice (version + auth)
    const first = await checkGhReady({ execFn: exec, ttlMs: 60_000, _now });
    expect(exec).toHaveBeenCalledTimes(2);
    expect(first).toEqual({ ok: true });

    // Second call at same timestamp: cache hit — execFn NOT called again
    const second = await checkGhReady({ execFn: exec, ttlMs: 60_000, _now });
    expect(exec).toHaveBeenCalledTimes(2); // still 2
    expect(second).toEqual({ ok: true });
  });
});

// ---------------------------------------------------------------------------
// C1: Broadened unauth patterns
// ---------------------------------------------------------------------------

describe('classifyStderr — broadened unauth patterns (C1)', () => {
  const patterns = [
    'HTTP 401 unauthorized',
    'HTTP 403 forbidden',
    'bad credentials',
    'invalid token',
    'insufficient scope',
  ];

  for (const stderr of patterns) {
    it(`classifies "${stderr}" as unauthed`, async () => {
      const exec = vi.fn().mockRejectedValue({ stderr, code: undefined, killed: false });
      try {
        await createPr({ base: 'main', head: 'feat', title: 'T', body: 'B' }, exec);
        throw new Error('Expected createPr to throw');
      } catch (e: unknown) {
        expect(e).toBeInstanceOf(GhError);
        expect((e as GhError).kind).toBe('unauthed');
      }
    });
  }
});

// ---------------------------------------------------------------------------
// P1: Failure results are NOT cached
// ---------------------------------------------------------------------------

describe('checkGhReady — failure not cached (P1)', () => {
  it('re-probes after a failed check even within the TTL window', async () => {
    let callCount = 0;
    const exec = vi.fn().mockImplementation(async () => {
      callCount++;
      if (callCount <= 1) throw new Error('first call fails');
      return { stdout: '', stderr: '' };
    });

    const fixedNow = Date.now();
    const opts = { execFn: exec, _now: () => fixedNow };

    const first = await checkGhReady(opts);
    expect(first.ok).toBe(false);

    // Second call — failure was NOT cached, so execFn must be called again
    const second = await checkGhReady(opts);
    expect(exec).toHaveBeenCalledTimes(3); // 1 for first (threw) + 2 for second (version + auth)
    expect(second.ok).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// P2: Timeout kind
// ---------------------------------------------------------------------------

describe('createPr — timeout kind (P2)', () => {
  it('throws GhError with kind "timeout" when exec is killed', async () => {
    const exec = vi.fn().mockRejectedValue({ killed: true, code: null, stderr: '' });
    try {
      await createPr({ base: 'main', head: 'feat', title: 'T', body: 'B' }, exec);
      throw new Error('Expected createPr to throw');
    } catch (e: unknown) {
      expect(e).toBeInstanceOf(GhError);
      expect((e as GhError).kind).toBe('timeout');
    }
  });
});

// ---------------------------------------------------------------------------
// T1: Non-ENOENT error in checkGhReady
// ---------------------------------------------------------------------------

describe('checkGhReady — non-ENOENT version error (T1)', () => {
  it('returns ok: false with "failed unexpectedly" hint on EACCES', async () => {
    const exec = vi.fn().mockRejectedValue({ code: 'EACCES' });
    const result = await checkGhReady({ execFn: exec, ttlMs: 0 });
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.hint).toMatch(/failed unexpectedly/);
    }
  });
});

// ---------------------------------------------------------------------------
// C5: In-flight dedup
// ---------------------------------------------------------------------------

describe('checkGhReady — in-flight dedup (C5)', () => {
  it('shares one probe when two calls arrive concurrently', async () => {
    const exec = vi.fn().mockResolvedValue({ stdout: '', stderr: '' });

    // Fire two calls simultaneously with no cache (ttlMs: 0)
    const [r1, r2] = await Promise.all([
      checkGhReady({ execFn: exec, ttlMs: 0 }),
      checkGhReady({ execFn: exec, ttlMs: 0 }),
    ]);

    // Both should succeed
    expect(r1.ok).toBe(true);
    expect(r2.ok).toBe(true);
    // Because of in-flight dedup, execFn should have been called only twice
    // (once for `gh --version`, once for `gh auth status`) — not 4 times.
    expect(exec).toHaveBeenCalledTimes(2);
  });
});

// ---------------------------------------------------------------------------
// postPrComment
// ---------------------------------------------------------------------------

describe('postPrComment', () => {
  it('success — feeds body via stdin, returns trimmed comment URL', async () => {
    const exec = vi
      .fn()
      .mockResolvedValue({ stdout: 'https://github.com/o/r/pull/5#issuecomment-1\n', stderr: '' });
    const url = await postPrComment({ pr: '5', body: '## Review\n- nit: foo' }, exec);
    expect(url).toBe('https://github.com/o/r/pull/5#issuecomment-1');
    // PR selector present, --body-file - reads stdin, body passed as 3rd arg.
    expect(exec).toHaveBeenCalledWith(
      'gh',
      ['pr', 'comment', '5', '--body-file', '-'],
      '## Review\n- nit: foo',
    );
  });

  it('empty pr selector — omits the ref so gh resolves the current branch PR', async () => {
    const exec = vi.fn().mockResolvedValue({ stdout: 'ok', stderr: '' });
    await postPrComment({ pr: '', body: 'b' }, exec);
    expect(exec).toHaveBeenCalledWith('gh', ['pr', 'comment', '--body-file', '-'], 'b');
  });

  it('unauthed stderr — throws GhError with kind: unauthed', async () => {
    const exec = vi
      .fn()
      .mockRejectedValue({ stderr: 'authentication required: please log in', exitCode: 1 });
    await expect(postPrComment({ pr: '5', body: 'b' }, exec)).rejects.toThrow(GhError);
    await expect(postPrComment({ pr: '5', body: 'b' }, exec)).rejects.toMatchObject({
      kind: 'unauthed',
    });
  });

  it('timeout (killed) — throws GhError with kind: timeout', async () => {
    const exec = vi.fn().mockRejectedValue({ killed: true, stderr: '' });
    await expect(postPrComment({ pr: '5', body: 'b' }, exec)).rejects.toMatchObject({
      kind: 'timeout',
    });
  });
});

// ---------------------------------------------------------------------------
// resolveCurrentBranchPr
// ---------------------------------------------------------------------------

describe('resolveCurrentBranchPr', () => {
  it('returns the trimmed PR number on success', async () => {
    const exec = vi.fn().mockResolvedValue({ stdout: '42\n', stderr: '' });
    expect(await resolveCurrentBranchPr(exec)).toBe('42');
    expect(exec).toHaveBeenCalledWith('gh', ['pr', 'view', '--json', 'number', '--jq', '.number']);
  });

  it('returns null when gh fails (no open PR for the branch)', async () => {
    const exec = vi.fn().mockRejectedValue(new Error('no pull requests found'));
    expect(await resolveCurrentBranchPr(exec)).toBeNull();
  });

  it('returns null when stdout is not a number', async () => {
    const exec = vi.fn().mockResolvedValue({ stdout: 'null\n', stderr: '' });
    expect(await resolveCurrentBranchPr(exec)).toBeNull();
  });
});
