/**
 * Open-PR action handler extracted from farm-callbacks.ts.
 *
 * Handles the `p` (Open PR) button on farm digest messages.
 * Extracted to keep farm-callbacks.ts under the 350-line ceiling (#832).
 *
 * @module telegram/handlers/farm-callbacks.open-pr
 */

import type { Context } from 'telegraf';
import {
  checkGhReady,
  createPr,
  GhError,
  type CreatePrOpts,
  type ExecFn,
  type GhReadiness,
} from '../../agent/gh.js';
import { recordPrCreated, type FarmManifest } from '../../agent/worktree.js';
import { resolveWinnerBranch } from '../../skills/score/winner.js';
import type { FarmCallbackDeps } from './farm-callbacks.js';
import { safeAnswer, type LogFn } from './farm-callbacks.helpers.js';

/**
 * Handle the Open PR (`p`) button.
 *
 * Idempotency: if a PR URL is already recorded in the manifest, acks with it
 * and returns -- no duplicate PR is opened.
 *
 * Contract: safeAnswer is called BEFORE any awaitable network work so the
 * callback ack beats Telegram's ~3 s deadline. Subsequent user-visible results
 * go through ctx.reply (which has no deadline).
 */
export async function handleOpenPr(
  ctx: Context,
  manifest: FarmManifest,
  deps: FarmCallbackDeps,
  log: LogFn,
): Promise<void> {
  // Idempotency: if a PR URL is already recorded, ack with it and return.
  if (manifest.prUrl) {
    await safeAnswer(ctx, `PR already open: ${manifest.prUrl}`, log);
    return;
  }

  // C2: Send progress ack BEFORE any awaitable network call so we beat
  // Telegram's ~3 s callback deadline even when gh is slow.
  await safeAnswer(ctx, 'Opening PR…', log);

  // Pre-flight: check gh is installed and authenticated.
  const ghReadyChecker = deps.checkGhReady ?? checkGhReady;
  let readiness: GhReadiness;
  try {
    readiness = await ghReadyChecker();
  } catch (err) {
    log('[farm-callback] checkGhReady threw:', err);
    // Progress ack ('Opening PR…') already fired -- use ctx.reply for this error.
    try { await ctx.reply('gh readiness check failed — see daemon logs'); } catch { /* ignored */ }
    return;
  }

  if (!readiness.ok) {
    // Progress ack already fired -- use ctx.reply for this error.
    try { await ctx.reply(readiness.hint); } catch { /* ignored */ }
    return;
  }

  // Resolve the winner branch (same logic as respawn / diff).
  const winnerResolver = deps.resolveWinnerBranch ?? resolveWinnerBranch;
  let winnerResult: Awaited<ReturnType<typeof resolveWinnerBranch>>;
  try {
    winnerResult = await winnerResolver(manifest);
  } catch (err) {
    log('[farm-callback] resolveWinnerBranch failed:', err);
    // Progress ack already fired -- use ctx.reply for this error.
    try { await ctx.reply('Winner lookup failed'); } catch { /* ignored */ }
    return;
  }

  const head = winnerResult.branch.branch;
  const base = manifest.baseBranch ?? 'main';
  const title = `Auto PR: ${manifest.taskName}`;
  const body = `Auto-generated by afk farm ${manifest.taskSlug} | winner: ${head} | created: ${new Date().toISOString()}`;

  const prCreator = deps.createPr ?? createPr;
  let prUrl: string;
  try {
    prUrl = await prCreator({ base, head, title, body });
  } catch (err) {
    if (err instanceof GhError) {
      // P2: include timeout kind in the exhaustive map
      const messages: Record<GhError['kind'], string> = {
        'not-found': 'gh CLI not found — install with: brew install gh',
        'already-exists': 'PR already exists for this branch',
        'unauthed': 'gh is not authenticated — run: gh auth login',
        'network': 'Network error — check gh connectivity',
        'timeout': 'gh timed out — check connectivity',
        'unknown': 'gh pr create failed — see daemon logs',
      };
      // Progress ack already fired -- use ctx.reply for this error.
      try { await ctx.reply(messages[err.kind]); } catch { /* ignored */ }
      return;
    }
    log('[farm-callback] createPr failed:', err);
    // Progress ack already fired -- use ctx.reply for this error.
    try { await ctx.reply('gh pr create failed — see daemon logs'); } catch { /* ignored */ }
    return;
  }

  // Record the PR in the manifest (best-effort: PR is already open).
  const recorder = deps.recordPrCreated ?? recordPrCreated;
  try {
    await recorder(manifest.taskSlug, prUrl);
  } catch (err) {
    log('[farm-callback] recordPrCreated failed:', err);
    // PR is open -- manifest is a log, not a gate. Continue to ack.
  }

  // The progress ack ('Opening PR…') already answered the callback; use
  // ctx.reply for the terminal success so both messages reach the user.
  try {
    await ctx.reply(`PR opened ✓\n🔗 ${prUrl}`);
  } catch (err) {
    log('[farm-callback] reply failed:', err);
  }
}

// Re-export types used only in this file so farm-callbacks.ts need not import them.
export type { CreatePrOpts, ExecFn };
