// Render + telemetry concern: snapshot markdown, telemetry JSONL.

import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import type { ImportKind, Inventory, TelemetryEntry, Diff } from './audit-sdk-dependency.types.js';
import { TRACKED_PACKAGES } from './audit-sdk-dependency.types.js';
import { hashSymbolSet } from './audit-sdk-dependency.lock.js';

const TELEMETRY_DIR = path.join(os.homedir(), '.afk', 'agent-framework');
const TELEMETRY_PATH = path.join(TELEMETRY_DIR, 'sdk-dependency-telemetry.jsonl');

export function renderSnapshot(inventory: Inventory, versions: { sdk: string | null }): string {
  const now = new Date().toISOString();
  const lines: string[] = [];
  lines.push('# SDK Dependency Snapshot');
  lines.push('');
  lines.push(`Generated: ${now}`);
  lines.push('');
  lines.push('## Versions');
  lines.push('');
  lines.push(`- \`@anthropic-ai/sdk\`: ${versions.sdk ?? '(not a dependency)'}`);
  lines.push('');

  const totalFiles = new Set<string>();
  for (const syms of inventory.values()) {
    for (const usage of syms.values()) {
      for (const f of usage.files) totalFiles.add(f);
    }
  }

  let totalRuntime = 0;
  let totalTypeOnly = 0;
  for (const syms of inventory.values()) {
    for (const usage of syms.values()) {
      if (usage.kind === 'runtime') totalRuntime += 1;
      else totalTypeOnly += 1;
    }
  }

  lines.push('## Summary');
  lines.push('');
  lines.push(`- **${totalFiles.size}** files import tracked Anthropic packages`);
  lines.push(`- **${totalRuntime}** runtime symbols, **${totalTypeOnly}** type-only symbols`);
  lines.push('');

  for (const pkg of TRACKED_PACKAGES) {
    const syms = inventory.get(pkg);
    lines.push(`## \`${pkg}\``);
    lines.push('');
    if (!syms || syms.size === 0) {
      lines.push('_No imports._');
      lines.push('');
      continue;
    }

    const pkgFiles = new Set<string>();
    let rt = 0;
    let ty = 0;
    for (const usage of syms.values()) {
      for (const f of usage.files) pkgFiles.add(f);
      if (usage.kind === 'runtime') rt += 1;
      else ty += 1;
    }
    lines.push(`- ${pkgFiles.size} files, ${rt} runtime symbols, ${ty} type-only symbols`);
    lines.push('');

    lines.push('### Symbols');
    lines.push('');
    lines.push('| Symbol | Kind | Files | Call sites |');
    lines.push('|---|---|---:|---:|');
    const sorted = [...syms.entries()].sort(
      (a, b) => (a[1].kind === b[1].kind ? 0 : a[1].kind === 'runtime' ? -1 : 1) || a[0].localeCompare(b[0]),
    );
    for (const [sym, usage] of sorted) {
      const calls = usage.kind === 'runtime' ? String(usage.callSites) : '\u2014';
      lines.push(`| \`${sym}\` | ${usage.kind} | ${usage.files.size} | ${calls} |`);
    }
    lines.push('');

    lines.push('### Files');
    lines.push('');
    const fileMap = new Map<string, Array<{ sym: string; kind: ImportKind }>>();
    for (const [sym, usage] of syms) {
      for (const f of usage.files) {
        let arr = fileMap.get(f);
        if (!arr) {
          arr = [];
          fileMap.set(f, arr);
        }
        arr.push({ sym, kind: usage.kind });
      }
    }
    const sortedFiles = [...fileMap.entries()].sort((a, b) => a[0].localeCompare(b[0]));
    lines.push('| File | Symbols |');
    lines.push('|---|---|');
    for (const [f, items] of sortedFiles) {
      items.sort((a, b) => a.sym.localeCompare(b.sym));
      const rendered = items.map((i) => `\`${i.sym}\`${i.kind === 'type-only' ? ' (type)' : ''}`).join(', ');
      lines.push(`| \`${f}\` | ${rendered} |`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('This file is regenerated by `pnpm audit:sdk`. Do not edit by hand.');
  lines.push('See `.sdk-dependency.lock.json` for the rationale of each tracked symbol.');
  lines.push('');
  return lines.join('\n');
}

export function buildTelemetry(
  inventory: Inventory,
  diff: Diff,
  versions: { sdk: string | null },
): TelemetryEntry {
  const totalFiles = new Set<string>();
  const perPackage: TelemetryEntry['per_package'] = {};
  for (const [pkg, syms] of inventory) {
    const pkgFiles = new Set<string>();
    let rt = 0;
    let ty = 0;
    for (const usage of syms.values()) {
      for (const f of usage.files) {
        pkgFiles.add(f);
        totalFiles.add(f);
      }
      if (usage.kind === 'runtime') rt += 1;
      else ty += 1;
    }
    perPackage[pkg] = { files: pkgFiles.size, runtime_symbols: rt, type_only_symbols: ty };
  }

  return {
    timestamp: new Date().toISOString(),
    surface: 'afk',
    sdk_version: versions.sdk,
    total_files: totalFiles.size,
    per_package: perPackage,
    symbol_hash: hashSymbolSet(inventory),
    new_symbols_since_last_run: diff.added,
    dropped_symbols_since_last_run: diff.dropped.map((d) => ({
      package: d.package,
      symbol: d.symbol,
    })),
    kind_changes_since_last_run: diff.kindChanges,
  };
}

export function appendTelemetry(entry: TelemetryEntry): void {
  fs.mkdirSync(TELEMETRY_DIR, { recursive: true });
  fs.appendFileSync(TELEMETRY_PATH, JSON.stringify(entry) + '\n', 'utf8');
}
